services:
  db:
    hostname: db
    image: juri/pgvector:16.2
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      #  - POSTGRES_HOST_AUTH_METHOD=trust
    #volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
